In [1]:
## numpy is numeric python

In [2]:
#!pip install numpy

In [3]:
import numpy as np

In [4]:
a=np.array([])
b=np.array([1,2,3,45,0])
c=np.array([[12,3,4],[4,5,8]])

In [6]:
a

array([], dtype=float64)

In [10]:
type(a)

numpy.ndarray

In [13]:
a.ndim

1

In [16]:
a.size

0

In [7]:
b

array([ 1,  2,  3, 45,  0])

In [11]:
type(b)

numpy.ndarray

In [14]:
b.ndim

1

In [17]:
b.size

5

In [9]:
#2-D array (matrix)
c

array([[12,  3,  4],
       [ 4,  5,  8]])

In [19]:
c.shape

(2, 3)

In [12]:
type(c)

numpy.ndarray

In [15]:
c.ndim

2

In [18]:
c.size

6

In [20]:
n=np.array([[2,3,4,5],[20,10,40,30],[200,100,600,700]])

In [21]:
n.shape

(3, 4)

In [22]:
n=[[2,3,4,5],[20,10,40,30],[200,100,600,700]]

In [23]:
n

[[2, 3, 4, 5], [20, 10, 40, 30], [200, 100, 600, 700]]

In [1]:
import numpy as np

In [20]:
m=np.array([[1,5,6,3],[7,4,8,9],[4,1,2,7]])

In [21]:
m[0][0]

1

In [22]:
m[0,0]

1

In [23]:
m

array([[1, 5, 6, 3],
       [7, 4, 8, 9],
       [4, 1, 2, 7]])

In [24]:
m[1,2]

8

In [25]:
m[2,0],m[2,1]

(4, 1)

In [27]:
m[2,0:2]

array([4, 1])

In [26]:
m[1:3,2:4]

array([[8, 9],
       [2, 7]])

In [28]:
m[1:,2:]

array([[8, 9],
       [2, 7]])

In [30]:
m[0:,3]

array([3, 9, 7])

In [29]:
m[1,:2]

array([7, 4])

# arange 

In [31]:
list(range(5,50,2))

[5,
 7,
 9,
 11,
 13,
 15,
 17,
 19,
 21,
 23,
 25,
 27,
 29,
 31,
 33,
 35,
 37,
 39,
 41,
 43,
 45,
 47,
 49]

In [32]:
np.arange(5,51)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [33]:
list(range(5.5,15.3))

TypeError: 'float' object cannot be interpreted as an integer

In [34]:
np.arange(5.5,50.3)

array([ 5.5,  6.5,  7.5,  8.5,  9.5, 10.5, 11.5, 12.5, 13.5, 14.5, 15.5,
       16.5, 17.5, 18.5, 19.5, 20.5, 21.5, 22.5, 23.5, 24.5, 25.5, 26.5,
       27.5, 28.5, 29.5, 30.5, 31.5, 32.5, 33.5, 34.5, 35.5, 36.5, 37.5,
       38.5, 39.5, 40.5, 41.5, 42.5, 43.5, 44.5, 45.5, 46.5, 47.5, 48.5,
       49.5])

In [35]:
np.arange(5.5,50.3,0.1)

array([ 5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. , 10.1, 10.2, 10.3, 10.4, 10.5, 10.6, 10.7, 10.8, 10.9,
       11. , 11.1, 11.2, 11.3, 11.4, 11.5, 11.6, 11.7, 11.8, 11.9, 12. ,
       12.1, 12.2, 12.3, 12.4, 12.5, 12.6, 12.7, 12.8, 12.9, 13. , 13.1,
       13.2, 13.3, 13.4, 13.5, 13.6, 13.7, 13.8, 13.9, 14. , 14.1, 14.2,
       14.3, 14.4, 14.5, 14.6, 14.7, 14.8, 14.9, 15. , 15.1, 15.2, 15.3,
       15.4, 15.5, 15.6, 15.7, 15.8, 15.9, 16. , 16.1, 16.2, 16.3, 16.4,
       16.5, 16.6, 16.7, 16.8, 16.9, 17. , 17.1, 17.2, 17.3, 17.4, 17.5,
       17.6, 17.7, 17.8, 17.9, 18. , 18.1, 18.2, 18.3, 18.4, 18.5, 18.6,
       18.7, 18.8, 18.9, 19. , 19.1, 19.2, 19.3, 19.4, 19.5, 19.6, 19.7,
       19.8, 19.9, 20. , 20.1, 20.2, 20.3, 20.4, 20

# reshape

In [36]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [37]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
np.arange(12).reshape(2,5)

ValueError: cannot reshape array of size 12 into shape (2,5)

In [42]:
m.max()

9

In [45]:
n=np.array([[1,5,66,3],[7,4,8,9],[4,1,2,7]])

In [46]:
n.argmax()

2

In [47]:
n*2

array([[  2,  10, 132,   6],
       [ 14,   8,  16,  18],
       [  8,   2,   4,  14]])

In [48]:
n+10

array([[11, 15, 76, 13],
       [17, 14, 18, 19],
       [14, 11, 12, 17]])

In [49]:
np.random.rand(2,2)

array([[0.31736682, 0.54043864],
       [0.83312641, 0.62119268]])

In [50]:
np.random.randn(2,2)

array([[ 0.32798307, -1.23023856],
       [-1.11595096, -1.49738534]])

In [51]:
np.random.randint(9,90,12)

array([33, 24, 81, 77, 21, 15, 14, 53, 83, 35, 77, 69])

In [56]:
s = np.random.randint(9,90,12).reshape(6,2)

In [57]:
s.sum()

565

In [58]:
s.sum(axis=1)

array([114, 106,  65,  75, 113,  92])

In [59]:
s

array([[70, 44],
       [26, 80],
       [19, 46],
       [50, 25],
       [72, 41],
       [17, 75]])

# 3D

In [62]:
d= np.array([[[4,40],[5,50],[6,60]],[[7,70],[8,80],[9,90]],[[5,55],[4,45],[6,65]]])

In [64]:
d.shape

(3, 3, 2)

In [ ]:
# 4,3,4  row column height

In [66]:
f= np.array([[[4,40,3,2],[5,50,3,2],[6,60,3,2]],[[7,70,3,2],[8,80,2,3],[9,90,3,3]],[[5,55,2,2],[4,45,3,4],[6,65,4,5]],[[4,40,3,2],[5,50,3,2],[6,60,3,2]]])

In [68]:
f

array([[[ 4, 40,  3,  2],
        [ 5, 50,  3,  2],
        [ 6, 60,  3,  2]],

       [[ 7, 70,  3,  2],
        [ 8, 80,  2,  3],
        [ 9, 90,  3,  3]],

       [[ 5, 55,  2,  2],
        [ 4, 45,  3,  4],
        [ 6, 65,  4,  5]],

       [[ 4, 40,  3,  2],
        [ 5, 50,  3,  2],
        [ 6, 60,  3,  2]]])

In [70]:
f.shape

(4, 3, 4)

# NAN not a number

In [71]:
x=np.array([12,56.,np.nan,66,100.,np.nan])

In [72]:
x

array([ 12.,  56.,  nan,  66., 100.,  nan])

In [73]:
x.dtype

dtype('float64')